# ruff: noqa: E501,I001
"""add user.onboarding_completed

Revision ID: 10ff6c5eb9f7
Revises: 8751a65acf13
Create Date: 2026-07-28 12:21:43.148495

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '10ff6c5eb9f7'
down_revision = '8751a65acf13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    # ### end Alembic commands ###
