# ruff: noqa: E501,I001
"""add post media dimensions and video poster

Revision ID: 21e8c71022d0
Revises: a24ffa957ea6
Create Date: 2026-08-31 21:27:15.506897

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '21e8c71022d0'
down_revision = 'a24ffa957ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_media', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('post_media', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('post_media', sa.Column('poster', sa.LargeBinary(), nullable=True))
    op.add_column('post_media', sa.Column('poster_content_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_media', 'poster_content_type')
    op.drop_column('post_media', 'poster')
    op.drop_column('post_media', 'height')
    op.drop_column('post_media', 'width')
    # ### end Alembic commands ###
