# ruff: noqa: E501,I001
"""add user.settings_revision

Revision ID: 8751a65acf13
Revises: 3188226cfd85
Create Date: 2026-07-27 11:27:24.019169

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '8751a65acf13'
down_revision = '3188226cfd85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('settings_revision', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'settings_revision')
    # ### end Alembic commands ###
