# ruff: noqa: E501,I001
"""add post and review history indexes

Revision ID: 910076030272
Revises: ff254fd0e9af
Create Date: 2026-08-02 21:35:03.526063

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '910076030272'
down_revision = 'ff254fd0e9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_post_reviews_user_created', 'post_reviews', ['user_id', 'created'], unique=False)
    op.create_index('ix_posts_author_created', 'posts', ['author_id', 'created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_author_created', table_name='posts')
    op.drop_index('ix_post_reviews_user_created', table_name='post_reviews')
    # ### end Alembic commands ###
