# ruff: noqa: E501,I001
"""add user subscriptions and post subscription snapshot

Revision ID: 97d1dc899f7e
Revises: 10ff6c5eb9f7
Create Date: 2026-07-30 21:21:50.672048

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '97d1dc899f7e'
down_revision = '10ff6c5eb9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', name='uq_user_subscription_user_kind')
    )
    op.add_column('posts', sa.Column('subscription_kind', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'subscription_kind')
    op.drop_table('user_subscriptions')
    # ### end Alembic commands ###
