# ruff: noqa: E501,I001
"""add user profile picture

Revision ID: f663e132cb13
Revises: 29181321c773
Create Date: 2026-08-20 22:14:06.331581

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'f663e132cb13'
down_revision = '29181321c773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('profile_picture_content_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_content_type')
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###
