# ruff: noqa: E501,I001
"""add supporter subscriptions

Revision ID: ff254fd0e9af
Revises: 97d1dc899f7e
Create Date: 2026-08-02 18:53:50.036359

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'ff254fd0e9af'
down_revision = '97d1dc899f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supporter_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('mollie_customer_id', sa.String(length=50), nullable=False),
    sa.Column('mollie_subscription_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supporter_subscriptions')
    # ### end Alembic commands ###
